apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging # Fluent-Bit DaemonSet이 배포된 네임스페이스와 동일하게 설정

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-reader
rules:
- apiGroups: [""] # 코어 API 그룹 (pods, namespaces, nodes 등)
  resources:
  - pods
  - namespaces
  - nodes
  verbs: ["get", "list", "watch"] # 파드, 네임스페이스, 노드 정보를 읽기 위한 필수 권한
- apiGroups: ["apps"] # Replicasets 정보도 필요한 경우 (filter_kubernetes가 사용하는 경우가 있음)
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-reader # 위에서 정의한 ClusterRole의 이름
subjects:
- kind: ServiceAccount
  name: fluent-bit # DaemonSet에서 사용하고 있는 ServiceAccount 이름
  namespace: logging # ServiceAccount가 정의된 네임스페이스