apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log 
        Exclude_Path      /var/log/containers/fluent-bit*.log,/var/log/containers/loki*.log,/var/log/containers/kube-apiserver*.log,/var/log/containers/kube-scheduler*.log,/var/log/containers/kube-controller-manager*.log
        Tag               kube.*
        Refresh_Interval  5
        Rotate_Wait       30
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        DB                /buffers/tail.db 
        Parser            docker

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log     Off
        Keep_Log      On
        Annotations   Off
        Labels        On
        Kube_URL      https://100.64.0.1:443

    # JSON 로그 파싱 (spring-app 로그가 이미 JSON 형태로 들어오면 유용)
    [FILTER]
        Name          parser
        Match         kube.*
        Key_Name      log
        Parser        logjson
        Reserve_Data  On
        # Preserve_Key  On


    [OUTPUT]
        Name            es
        Match           kube.var.log.containers.spring-app*
        Host            10.0.10.30
        Port            9200
        Include_Tag_Key On
        Index           k8s-logs
        Logstash_Format On
        Logstash_Prefix k8s-logs
        Suppress_Type_Name On
        Tag_Key         @tag

    [OUTPUT]
        Name            es
        Match           kube.*
        Host            10.0.10.30
        Port            9200
        Include_Tag_Key On
        Index           k8s-logs
        Logstash_Format On
        Logstash_Prefix k8s-logs
        Suppress_Type_Name On
        Tag_Key         @tag


    # 모든 로그 → S3
    [OUTPUT]
        Name              s3
        Match             kube.*,kube.var.log.containers.*
        bucket            k8s-fluentd-clobee-bucket
        region            ap-northeast-2
        total_file_size   10M
        upload_timeout    30s
        store_dir         /buffers
        s3_key_format     /logs/$TAG/%Y/%m/%d/%H/%M/%S.gz
        compression       gzip

    # [OUTPUT]
    #     Name            stdout
    #     Match           kube.var.log.containers.spring-app*

    # [OUTPUT]
    #     Name            stdout
    #     Match           kube.var.log.containers.*



  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        logjson
        Format      json
        # Time_Key    @timestamp
        # Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        # Time_Keep   On
