apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
    name: clbee.k8s.local
spec:
    cloudProvider: aws
    region: ap-northeast-2
    networking:
        calico: {}
        nonMasqueradeCIDR: 100.64.0.0/10
    kubernetesVersion: '1.27.3'
    api:
        loadBalancer:
            type: Public

    subnets:
        - name: apne2-public
          zone: ap-northeast-2a
          type: Public
          id: ${terraform.output.public_subnet1_id}
        - name: apne2-private-a
          zone: ap-northeast-2a
          type: Private
          id: ${terraform.output.private_subnet1_id}
        - name: apne2-private-b
          zone: ap-northeast-2a
          type: Private
          id: ${terraform.output.private_subnet2_id}

    nodePools:
        - name: frontend
          instanceGroup: frontend
          nodeCount: 1
          instanceType: t3.micro
          subnets:
              - apne2-public-a
        - name: master
          instanceGroup: master
          nodeCount: 1
          instanceType: t3.medium
          subnets:
              - apne2-private-a
        - name: backend
          instanceGroup: backend
          nodeCount: 3
          instanceType: t3.micro
          subnets:
              - apne2-private-b

    etcdClusters:
        - name: main
          etcdMembers:
              - name: a
                instanceGroup: master
    additionalNetworkCIDRs:
        - 10.0.0.0/16
    networkCIDR: 10.0.0.0/16
    vpc: ${terraform.output.vpc_id}
    provider: aws
