apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    # [SERVICE] 블록: Fluent Bit 전역 설정
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    # [INPUT] 블록: 수집할 로그 파일 정의
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Refresh_Interval  5
        Rotate_Wait       30
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db
        Parser            docker

    # [FILTER] 블록: Kubernetes 메타데이터 추가
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    # [OUTPUT] 블록: 수집된 로그를 Fluentd로 포워딩
    [OUTPUT]
        Name  forward
        Match *
        Host  fluentd.logging.svc.cluster.local
        Port  24224

  parsers.conf: |
    # [PARSER] 블록: JSON 로그 파서 정의
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---