apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Rotate_Wait       30
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db

    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Keep_Log          Off
        Annotations       Off
        Labels            On
        Kube_URL          https://100.64.0.1:443

    # S3에 모든 로그 저장
    [OUTPUT]
        Name              s3
        Match             kube.*
        bucket            k8s-fluentd-clobee-bucket
        region            ap-northeast-2
        total_file_size   10M
        upload_timeout    30m
        store_dir         /buffers
        s3_key_format     /logs/all/%Y/%m/%d/%H/%M_%S.gz
        compression       gzip

    # ES에 모든 로그 전송 (인덱스는 날짜별 자동 생성)
    [OUTPUT]
        Name              es
        Match             kube.*
        Host              ${ES_HOST}
        Port              ${ES_PORT}   
        Include_Tag_Key   On
        Index             k8s-logs
        Suppress_Type_Name On
        Tag_Key           @tag

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On