apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
      @label @ROUTER
    </source>

    <label @ROUTER>
      <match **>
        @type rewrite_tag_filter
        <rule>
          key kubernetes.labels.app
          pattern ^spring-app$
          tag spring
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*backend.*$
          tag backend
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*harbor.*$
          tag harbor
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*master.*$
          tag master
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*frontend.*$
          tag frontend
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*bastion.*$
          tag bastion
        </rule>
        <rule>
          key kubernetes.node_name
          pattern ^ip-.*$
          tag infra
        </rule>
      </match>

      <match spring>
        @type relabel
        @label @SPRING
      </match>

      <match backend>
        @type relabel
        @label @BACKEND
      </match>

      <match harbor>
        @type relabel
        @label @HARBOR
      </match>

      <match master>
        @type relabel
        @label @MASTER
      </match>

      <match frontend>
        @type relabel
        @label @FRONTEND
      </match>

      <match bastion>
        @type relabel
        @label @BASTION
      </match>

      <match infra>
        @type relabel
        @label @INFRA
      </match>
    </label>

    <label @SPRING>
      <filter **>
        @type grep
        <exclude>
          key level
          pattern /^(INFO|DEBUG)$/
        </exclude>
      </filter>

      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_spring
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/spring/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_spring
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>

    <label @BACKEND>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_backend
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/backend/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_backend
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>

    <label @HARBOR>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_harbor
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/harbor/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_harbor
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>


    <label @MASTER>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   tag_key tag
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_master
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/master/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_master
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>

    <label @FRONTEND>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   tag_key tag
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_frontend
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/frontend/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_frontend
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>

    <label @BASTION>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   tag_key tag
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_bastion
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/bastion/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_bastion
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>

    <label @INFRA>
      # <match **>
      #   @type elasticsearch
      #   host 192.168.0.100
      #   port 9200
      #   logstash_format true
      #   include_tag_key true
      #   type_name fluentd
      #   flush_interval 10s
      #   buffer_path /fluentd/buffer/es_infra
      #   <buffer>
      #     flush_interval 10s
      #     retry_type exponential_backoff
      #     retry_wait 1s
      #     retry_max_interval 30s
      #     retry_forever true
      #   </buffer>
      # </match>

      <match **>
        @type s3
        aws_key_id #{ENV['AWS_ACCESS_KEY_ID']}
        aws_sec_key #{ENV['AWS_SECRET_ACCESS_KEY']}
        s3_bucket k8s-fluentd-clobee-bucket
        s3_region ap-northeast-2
        path logs/infra/%Y/%m/%d/
        buffer_path /fluentd/buffer/s3_infra
        time_slice_format %Y%m%d%H
        time_slice_wait 10m
        compress gzip
        <buffer time>
          timekey 1h
          timekey_wait 10m
          flush_interval 5m
        </buffer>
        include_tag_key true
        tag_key tag
      </match>
    </label>
