apiVersion: v1
data:
  API_KEY: TkNTOUw3RlcwTlZLSFpVTw==
  API_SECRET: WEMxUUVMWFFRVEgyWk5IUTVZVUVYR0VFNUFZVTVZWkY=
  DB_PASSWORD: Y2xvdmVyMQ==
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vYXAubG9jbHguaW86NTMwMzkvY2xvYmVlREI=
  DB_USERNAME: Y2xvYmVl
  JWT_SECRET: cXB3b2V0aGFzZGxmbnF0ZXBpdWhzYWRmbnF3ZXRsYXNkbmZwb3dldGJhd2RsZnNuZHR1cXdwZW5ma2FzbGRmYXNkZnFld3Rhc2RmYWV3U0RmdHdxc2FkZnE=
  KAKAO_CLIENT_ID: NTU4MjMwZjVhZTg5ZjY5NjY4N2NhMTA4N2M0NGNhZjg=
  KAKAO_CLIENT_SECRET: RmdyenExOWJTemsyWjdZcGlla1VHMm5QeE9pR0F2UGs=
  REDIS_HOST: YXAubG9jbHguaW8=
  REDIS_PASSWORD: Y2xvdmVyMg==
  REDIS_PORT: NTY4Nw==
  SENDER_PHONE: MDEwMjQ3MDg3MDEgICAgIyBDb29sU01T7JeQIOuTseuhne2VnCDrsJzsi6DrsojtmLg=
kind: Secret
metadata:
  creationTimestamp: null
  name: spring-env-secret
